version: '2'
services:
    ravisampleapplication-mongodb:
        image: mongo:3.6.3
        ports:
            - "27017:27017"
        command: mongos --configdb ravisampleapplication-mongodb-config
    ravisampleapplication-mongodb-node:
        build:
            context: .
            dockerfile: mongodb/MongoDB.Dockerfile
        command: mongod --replSet rs1 --noprealloc --smallfiles
    ravisampleapplication-mongodb-config:
        image: mongo:3.6.3
        container_name: ravisampleapplication-mongodb-config
        command: mongod --noprealloc --smallfiles --configsvr --dbpath /data/db
